project:
  type: website
  #output-dir: docs
  resources:
    - "*.docx"

website:
  page-navigation: true
  title: "STAT 313 - Spring 2023"
  description: "Homepage for STAT 313 - Applied Experimental Design and Regression Models at Cal Poly, Spring 2023."
  #site-url: "https://atheobold.github.io/stat-313-website"
  #repo-url: https://github.com/atheobold/stat-313-website
  #repo-actions: [issue]

  #open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Allison Theobold"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/cp-stat-hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/atheobold/stat-313-website
        text: "GitHub organization"
      - icon: cloud-fill
        href: https://posit.cloud/spaces/352796/join?access_code=1UXvC0avaZPdFlXCzQUZqFAUdLgGFehApPhyVxjo
        aria-label: RStudio Cloud
      - icon: person-fill
        href: https://canvas.calpoly.edu
        text: "Cal Poly Canvas"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
      - section: "R Resources"
        contents:
          - href: course_resources.qmd
            text: R Resources
      - section: "Projects"
        contents:
          - href: project/midterm-project-directions.qmd
            text: Midterm Project Description
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual